name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to trigger it manually anytime

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate and Commit Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AyushBaware
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: commit
          filename: profile/activity-graph.svg # Natively saves and commits right inside your profile folder
