name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AyushBaware
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: commit
          filename: profile-activity-graph.svg

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          
          mkdir -p profile
          mv ./profile-activity-graph.svg ./profile/activity-graph.svg
          
          git add ./profile/activity-graph.svg
          git commit -m "Update activity graph" || exit 0
          git push
